FROM busybox:latest

LABEL meowkov=yes

COPY meowkov /

# Add missing CA information for TLS connections
COPY ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

RUN echo "nobody:x:65534:65534:nobody:/:/bin/false" >> /etc/passwd && \
    echo "nobody:x:65534:" >> /etc/group

USER nobody

ENTRYPOINT ["/meowkov"]
